### ISSUE TITLE
[Bug] Cannot edit the header title

### ISSUE THREAD

**Issue by emisjerry** [1C0D/Obsidian-Reveal-File-in-explorer#3]
1. Before installing, i can edit the filename in the header title, left / right arrow keys can move the cursor.
After installing, it cannot be edit in header title.

2. If the opened file in the bottom of a file explorer folder, when i click the header title, the folder will expand and scrollbar appears. But the filename cannot be seen if i don't scroll down.

**Comment by 1C0D** [comment]
1. I put a warning in the README, because it's a side effect, I can't control for the moment. Prefer inLine Title (the main title (header1)) to edit your file title/name. The focus is going on the explorer, maybe later I find how to get it back to header title.
2. you can allow option to reduce other folders when revealing. It should prevent from this. it was the aim at least

**Comment by 1C0D** [comment]
@emisjerry the problem about title is now fixed.
