### ISSUE TITLE
Seems to break Notion-Like Tables

### ISSUE THREAD

**Issue by azuryst** [1C0D/Obsidian-Reveal-File-in-explorer#6]
I love this plugin, but it seems to cause issues with the Notion-Like Tables plugin. Text in text columns become hidden when navigating back and forth among tables and other notes. Once I disabled this plugin, the text in the Notion-Like Tables appears normal again and issues seem to be resolved.

<img src="https://github.com/1C0D/Obsidian-Reveal-File-in-explorer/assets/6332446/7960f3f0-0dab-421a-8046-a5dc4c3ed56d" width="600">
<img src="https://github.com/1C0D/Obsidian-Reveal-File-in-explorer/assets/6332446/fa4165d6-e23b-4366-89a9-a043ed1903b0" width="600">

**Comment by 1C0D** [comment]
the bug is coming from the native reveal function. "reveal current file in navigation" in the palette
Can you open an issue on the github of the plugin ? ask them to see if it's linked to their plugin.
I do a fix to not reveal on opening, when it's a file *.table. So it will be ok on this type of page.
Maybe this is linked to the type of leaf this is creating, "notion-like-tables". I checked with the type "excalidraw" it is working.
